name: CI_Push_Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  check_commits_convention:
    name: Check Conventional Commits Message
    runs-on: ubuntu-latest

    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:feat|fix|chore|test|docs|build|ci|style|refactor|perf|revert|hotfix)(?:\(\w+\))?:\s[a-z]{1,2}.+|^Merge branch .+ into .+$'
          error: 'The commit message must have the following structure: <type>(?): <description>'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  check_branches_convention:
    name: Check Conventional Branches Name
    runs-on: ubuntu-latest

    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z]+)/([a-z]+)'
          allowed_prefixes: 'feature,bugfix,hotfix,build,ci,docs,chore,stable,refactor,perf,'
          ignore: main,develop
          min_length: 4
          max_length: 100

  deploy_to_s3:
    name: Deploy to S3
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to AWS S3
        run: |
          # Example AWS CLI command to upload files to S3
          aws s3 cp ./build/ s3://$AWS_BUCKET_NAME/ --recursive --region $AWS_REGION
        # Ensure the AWS CLI is installed and configured
